// Audit log action constants

export const AUDIT_ACTIONS = {
  // User Management Actions
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_REACTIVATED: 'USER_REACTIVATED',

  // Authentication Actions
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_REGISTER: 'USER_REGISTER',
  LOGIN_FAILED: 'LOGIN_FAILED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',

  // Password Actions
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',

  // Email Actions
  EMAIL_VERIFICATION_SENT: 'EMAIL_VERIFICATION_SENT',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  EMAIL_VERIFICATION_FAILED: 'EMAIL_VERIFICATION_FAILED',

  // Profile Actions
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  PROFILE_VIEWED: 'PROFILE_VIEWED',
  EMAIL_CHANGED: 'EMAIL_CHANGED',


  // Security Actions
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  INVALID_TOKEN_USED: 'INVALID_TOKEN_USED',

  // Admin Actions (for future use)
  ADMIN_USER_CREATED: 'ADMIN_USER_CREATED',
  ADMIN_USER_DELETED: 'ADMIN_USER_DELETED',
  ADMIN_SETTINGS_CHANGED: 'ADMIN_SETTINGS_CHANGED',
  ADMIN_DATA_EXPORTED: 'ADMIN_DATA_EXPORTED',

  // System Actions
  SYSTEM_BACKUP_CREATED: 'SYSTEM_BACKUP_CREATED',
  SYSTEM_MAINTENANCE_START: 'SYSTEM_MAINTENANCE_START',
  SYSTEM_MAINTENANCE_END: 'SYSTEM_MAINTENANCE_END',

  // Data Actions
  DATA_IMPORTED: 'DATA_IMPORTED',
  DATA_EXPORTED: 'DATA_EXPORTED',
  DATA_MIGRATED: 'DATA_MIGRATED',
  DATA_PURGED: 'DATA_PURGED',
} as const;

export const AUDIT_ENTITIES = {
  USER: 'User',
  PROFILE: 'Profile',
  SESSION: 'Session',
  TOKEN: 'Token',
  EMAIL: 'Email',
  SYSTEM: 'System',
  ADMIN: 'Admin',
  BACKUP: 'Backup',
  SETTINGS: 'Settings',
} as const;

export const AUDIT_RESULTS = {
  SUCCESS: true,
  FAILURE: false,
} as const;

// Type definitions for constants
export type AuditAction = typeof AUDIT_ACTIONS[keyof typeof AUDIT_ACTIONS];
export type AuditEntity = typeof AUDIT_ENTITIES[keyof typeof AUDIT_ENTITIES];
export type AuditResult = typeof AUDIT_RESULTS[keyof typeof AUDIT_RESULTS];