// Error code constants for consistent error handling

export const ERROR_CODES = {
  // Base Error Codes
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
  CONFLICT_ERROR: 'CONFLICT_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE_ERROR: 'SERVICE_UNAVAILABLE_ERROR',

  // Authentication Error Codes
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_ACCOUNT_DEACTIVATED: 'AUTH_ACCOUNT_DEACTIVATED',
  AUTH_USER_EXISTS: 'AUTH_USER_EXISTS',
  AUTH_PASSWORD_MISMATCH: 'AUTH_PASSWORD_MISMATCH',
  AUTH_WEAK_PASSWORD: 'AUTH_WEAK_PASSWORD',
  AUTH_RESET_TOKEN_NOT_FOUND: 'AUTH_RESET_TOKEN_NOT_FOUND',
  AUTH_RESET_TOKEN_USED: 'AUTH_RESET_TOKEN_USED',
  AUTH_TOO_MANY_RESET_ATTEMPTS: 'AUTH_TOO_MANY_RESET_ATTEMPTS',
  AUTH_VERIFICATION_TOKEN_NOT_FOUND: 'AUTH_VERIFICATION_TOKEN_NOT_FOUND',
  AUTH_VERIFICATION_TOKEN_USED: 'AUTH_VERIFICATION_TOKEN_USED',
  AUTH_EMAIL_ALREADY_VERIFIED: 'AUTH_EMAIL_ALREADY_VERIFIED',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_CURRENT_PASSWORD_INCORRECT: 'AUTH_CURRENT_PASSWORD_INCORRECT',
  AUTH_TOO_MANY_SESSIONS: 'AUTH_TOO_MANY_SESSIONS',
  AUTH_SERVICE_ERROR: 'AUTH_SERVICE_ERROR',
  AUTH_TOKEN_GENERATION_ERROR: 'AUTH_TOKEN_GENERATION_ERROR',
  AUTH_HASHING_ERROR: 'AUTH_HASHING_ERROR',

  // User Error Codes
  USERS_PROFILE_NOT_FOUND: 'USERS_PROFILE_NOT_FOUND',
  USERS_INVALID_DATA: 'USERS_INVALID_DATA',
  USERS_EMAIL_IN_USE: 'USERS_EMAIL_IN_USE',
  USERS_ACCOUNT_ALREADY_DEACTIVATED: 'USERS_ACCOUNT_ALREADY_DEACTIVATED',
  USERS_ACCOUNT_DELETION_ERROR: 'USERS_ACCOUNT_DELETION_ERROR',
  USERS_PROFILE_UPDATE_ERROR: 'USERS_PROFILE_UPDATE_ERROR',
  USERS_INVALID_NAME: 'USERS_INVALID_NAME',
  USERS_INVALID_EMAIL_FORMAT: 'USERS_INVALID_EMAIL_FORMAT',
  USERS_INSUFFICIENT_PERMISSIONS: 'USERS_INSUFFICIENT_PERMISSIONS',
  USERS_SELF_MODIFICATION_ERROR: 'USERS_SELF_MODIFICATION_ERROR',
  USERS_SERVICE_ERROR: 'USERS_SERVICE_ERROR',
  USERS_STATS_ERROR: 'USERS_STATS_ERROR',
  USERS_SESSION_NOT_FOUND: 'USERS_SESSION_NOT_FOUND',
  USERS_SESSION_EXPIRED: 'USERS_SESSION_EXPIRED',
  USERS_TOO_MANY_SESSIONS: 'USERS_TOO_MANY_SESSIONS',

  // Health Error Codes
  HEALTH_CHECK_FAILED: 'HEALTH_CHECK_FAILED',
  HEALTH_DATABASE_ERROR: 'HEALTH_DATABASE_ERROR',
  HEALTH_DATABASE_CONNECTION_ERROR: 'HEALTH_DATABASE_CONNECTION_ERROR',
  HEALTH_DATABASE_TIMEOUT: 'HEALTH_DATABASE_TIMEOUT',
  HEALTH_SYSTEM_ERROR: 'HEALTH_SYSTEM_ERROR',
  HEALTH_MEMORY_ERROR: 'HEALTH_MEMORY_ERROR',
  HEALTH_APPLICATION_ERROR: 'HEALTH_APPLICATION_ERROR',
  HEALTH_NOT_READY: 'HEALTH_NOT_READY',
  HEALTH_DEPENDENCY_NOT_READY: 'HEALTH_DEPENDENCY_NOT_READY',
  HEALTH_METRICS_ERROR: 'HEALTH_METRICS_ERROR',
  HEALTH_LOG_METRICS_ERROR: 'HEALTH_LOG_METRICS_ERROR',
  HEALTH_USER_STATS_ERROR: 'HEALTH_USER_STATS_ERROR',
  HEALTH_SERVICE_ERROR: 'HEALTH_SERVICE_ERROR',

  // Email Error Codes
  EMAIL_CONFIGURATION_ERROR: 'EMAIL_CONFIGURATION_ERROR',
  EMAIL_SMTP_CONFIGURATION_ERROR: 'EMAIL_SMTP_CONFIGURATION_ERROR',
  EMAIL_SEND_ERROR: 'EMAIL_SEND_ERROR',
  EMAIL_TEMPLATE_ERROR: 'EMAIL_TEMPLATE_ERROR',
  EMAIL_VALIDATION_ERROR: 'EMAIL_VALIDATION_ERROR',
  EMAIL_SMTP_CONNECTION_ERROR: 'EMAIL_SMTP_CONNECTION_ERROR',
  EMAIL_SMTP_AUTH_ERROR: 'EMAIL_SMTP_AUTH_ERROR',
  EMAIL_SMTP_TIMEOUT: 'EMAIL_SMTP_TIMEOUT',
  EMAIL_RATE_LIMIT_EXCEEDED: 'EMAIL_RATE_LIMIT_EXCEEDED',
  EMAIL_QUOTA_EXCEEDED: 'EMAIL_QUOTA_EXCEEDED',
  EMAIL_CONTENT_ERROR: 'EMAIL_CONTENT_ERROR',
  EMAIL_ATTACHMENT_ERROR: 'EMAIL_ATTACHMENT_ERROR',
  EMAIL_DELIVERY_ERROR: 'EMAIL_DELIVERY_ERROR',
  EMAIL_BOUNCE_ERROR: 'EMAIL_BOUNCE_ERROR',
  EMAIL_SPAM_ERROR: 'EMAIL_SPAM_ERROR',
  EMAIL_LOG_ERROR: 'EMAIL_LOG_ERROR',
  EMAIL_SERVICE_ERROR: 'EMAIL_SERVICE_ERROR',
  EMAIL_SERVICE_UNAVAILABLE: 'EMAIL_SERVICE_UNAVAILABLE',

  // Database Error Codes
  DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
  DATABASE_QUERY_ERROR: 'DATABASE_QUERY_ERROR',
  DATABASE_CONSTRAINT_ERROR: 'DATABASE_CONSTRAINT_ERROR',
  DATABASE_TIMEOUT_ERROR: 'DATABASE_TIMEOUT_ERROR',
  DATABASE_TRANSACTION_ERROR: 'DATABASE_TRANSACTION_ERROR',
  DATABASE_MIGRATION_ERROR: 'DATABASE_MIGRATION_ERROR',

  // System Error Codes
  SYSTEM_CONFIGURATION_ERROR: 'SYSTEM_CONFIGURATION_ERROR',
  SYSTEM_RESOURCE_ERROR: 'SYSTEM_RESOURCE_ERROR',
  SYSTEM_PERMISSION_ERROR: 'SYSTEM_PERMISSION_ERROR',
  SYSTEM_DEPENDENCY_ERROR: 'SYSTEM_DEPENDENCY_ERROR',
  SYSTEM_TIMEOUT_ERROR: 'SYSTEM_TIMEOUT_ERROR',

  // Network Error Codes
  NETWORK_CONNECTION_ERROR: 'NETWORK_CONNECTION_ERROR',
  NETWORK_TIMEOUT_ERROR: 'NETWORK_TIMEOUT_ERROR',
  NETWORK_DNS_ERROR: 'NETWORK_DNS_ERROR',
  NETWORK_SSL_ERROR: 'NETWORK_SSL_ERROR',

  // Cache Error Codes
  CACHE_CONNECTION_ERROR: 'CACHE_CONNECTION_ERROR',
  CACHE_TIMEOUT_ERROR: 'CACHE_TIMEOUT_ERROR',
  CACHE_MEMORY_ERROR: 'CACHE_MEMORY_ERROR',
  CACHE_SERIALIZATION_ERROR: 'CACHE_SERIALIZATION_ERROR',

  // File System Error Codes
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_PERMISSION_ERROR: 'FILE_PERMISSION_ERROR',
  FILE_SIZE_ERROR: 'FILE_SIZE_ERROR',
  FILE_TYPE_ERROR: 'FILE_TYPE_ERROR',
  FILE_UPLOAD_ERROR: 'FILE_UPLOAD_ERROR',

  // API Error Codes
  API_RATE_LIMIT_EXCEEDED: 'API_RATE_LIMIT_EXCEEDED',
  API_QUOTA_EXCEEDED: 'API_QUOTA_EXCEEDED',
  API_INVALID_REQUEST: 'API_INVALID_REQUEST',
  API_MALFORMED_REQUEST: 'API_MALFORMED_REQUEST',
  API_UNSUPPORTED_VERSION: 'API_UNSUPPORTED_VERSION',

  // Generic Error Codes
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  OPERATION_FAILED: 'OPERATION_FAILED',
  RESOURCE_LOCKED: 'RESOURCE_LOCKED',
  OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
  FEATURE_NOT_IMPLEMENTED: 'FEATURE_NOT_IMPLEMENTED',
} as const;

export const ERROR_CATEGORIES = {
  AUTHENTICATION: 'authentication',
  AUTHORIZATION: 'authorization',
  VALIDATION: 'validation',
  DATABASE: 'database',
  NETWORK: 'network',
  SYSTEM: 'system',
  BUSINESS_LOGIC: 'business_logic',
  EXTERNAL_SERVICE: 'external_service',
  CONFIGURATION: 'configuration',
  SECURITY: 'security',
} as const;

export const ERROR_SEVERITY = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical',
} as const;

export const ERROR_RECOVERY_ACTIONS = {
  RETRY: 'retry',
  FALLBACK: 'fallback',
  SKIP: 'skip',
  ABORT: 'abort',
  ESCALATE: 'escalate',
  MANUAL_INTERVENTION: 'manual_intervention',
} as const;

// Type definitions
export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
export type ErrorCategory = typeof ERROR_CATEGORIES[keyof typeof ERROR_CATEGORIES];
export type ErrorSeverity = typeof ERROR_SEVERITY[keyof typeof ERROR_SEVERITY];
export type ErrorRecoveryAction = typeof ERROR_RECOVERY_ACTIONS[keyof typeof ERROR_RECOVERY_ACTIONS];